# Copyright (c) Microsoft Corporation.
# Licensed under the MIT License.

---

- name:                                "Restart waagent"
  ansible.builtin.service:
    name:                              waagent
    state:                             restarted

- name:                                "Swap reboot"
  become:                              true
  become_user:                         root
  ansible.builtin.reboot:
    reboot_timeout:                    300
    post_reboot_delay:                 10
  failed_when:                         false
  listen: "Swap reboot"

- name:                                "1.1 Swap: - Clear the failed state of hosts"
  ansible.builtin.meta:                clear_host_errors
  listen: "Swap reboot"

- name:                                "1.1 Swap: - Wait for system to become reachable"
  ansible.builtin.wait_for_connection:
    delay:                             10
    timeout:                           300
  listen: "Swap reboot"
