# Copyright (c) Microsoft Corporation.
# Licensed under the MIT License.

---
# TODO: Maybe move these to a group_vars/all/distro file so that they
# can be shared by all playbooks/tasks automatically, and extend with
# standardised versions of all similar patterns used in the playbooks.
# Changed from ansible_os_family to ansible_distribution to adopt Oracle Linux. os_family returns returns value Redhat by default.
distro_name:    "{{ ansible_distribution | upper }}-{{ ansible_distribution_major_version }}"
distribution_id:      "{{ ansible_distribution | lower ~ ansible_distribution_major_version }}"
distribution_full_id: "{{ ansible_distribution | lower ~ ansible_distribution_version }}"

# Swap configuration method: 'waagent' or 'cloud-init'
swap_config_type: "cloud-init"

# Default swap size in MB (can be overridden by sap_swap variable)
default_swap_size_mb: 2048

# Whether to use fallocate or dd for cloud-init swap file creation
use_fallocate: true
