# Copyright (c) Microsoft Corporation.
# Licensed under the MIT License.

# /*----------------------------------------------------------------------------8
# |                                                                            |
# |            Role for ensuring the swap space is configured correctly         |
# |                                                                            |
# +------------------------------------4--------------------------------------*/
---
# -------------------------------------+---------------------------------------8
#
# Task: 1.1     - swap space setup orchestrator
#
# -------------------------------------+---------------------------------------8

- name:                                "1.1 Swap: - Ensure /mnt/resource directory exists"
  ansible.builtin.file:
    path:                              "/mnt/resource"
    state:                             directory
    mode:                              "0755"

- name:                                "1.1 Swap: - Ensure /mnt directory exists"
  ansible.builtin.file:
    path:                              "/mnt"
    state:                             directory
    mode:                              "0755"

# Check the current swap size
- name:                                "1.1 Swap: - Check current swap size"
  ansible.builtin.shell:               set -o pipefail && cat /proc/meminfo | grep SwapTotal
  register:                            swap_space
  changed_when:                        false

- name:                                "1.1 Swap: - Debug swap space from /proc/meminfo"
  ansible.builtin.debug:
    msg:                               "SWAP size from procinfo: {{ swap_space }}"
    verbosity:                         2

- name:                                "1.1 Swap: - Extract swap value"
  ansible.builtin.set_fact:
    swap_value:                        "{{ swap_space.stdout_lines[0] | regex_search('([0-9]+)') }}"

- name:                                "1.1 Swap: - Convert swap space to integer"
  ansible.builtin.set_fact:
    swap_size:                         "{{ swap_value | int }}"

- name:                                "1.1 Swap: - Debug current swap size"
  ansible.builtin.debug:
    msg:                               "Current swap size: {{ swap_size }}"

- name:                                "1.1 Swap: - Determine target swap size"
  ansible.builtin.set_fact:
    target_swap_size_mb:               "{{ (sap_swap | selectattr('tier', 'search', node_tier) | list | first).swap_size_mb | default(default_swap_size_mb) }}"

- name:                                "1.1 Swap: - Debug target swap size"
  ansible.builtin.debug:
    msg:                               "Target swap size: {{ target_swap_size_mb }}MB, Config type: {{ swap_config_type }}"

# Route to appropriate configuration method
- name:                                "1.1 Swap: - Configure swap using waagent"
  when:
                                       - swap_config_type == "waagent"
                                       - swap_size == '0'
  ansible.builtin.include_tasks:       waagent.yaml

- name:                                "1.1 Swap: - Configure swap using cloud-init"
  when:
                                       - swap_config_type == "cloud-init"
                                       - swap_size == '0'
  ansible.builtin.include_tasks:       cloud-init.yaml

- name:                                "1.1 Swap: - Swap already configured"
  ansible.builtin.debug:
    msg:                               "Swap is already configured with {{ swap_size }}KB"
  when:                                swap_size != '0'

...
